using System.Text.Json.Serialization;

namespace Ovh.Api.Models;

public enum TaskFunction
{
    [JsonStringEnumMemberName("INFRA_002_VirtualNetworkInterface")]
    Infra002VirtualNetworkInterface,
    [JsonStringEnumMemberName("INFRA_002_VirtualNetworkInterface_group")]
    Infra002VirtualNetworkInterfaceGroup,
    [JsonStringEnumMemberName("INFRA_002_VirtualNetworkInterface_ungroup")]
    Infra002VirtualNetworkInterfaceUngroup,
    [JsonStringEnumMemberName("INFRA_ONE_NETWORK_ONEAPI_VirtualNetworkInterface_group")]
    InfraOneNetworkOneapiVirtualNetworkInterfaceGroup,
    [JsonStringEnumMemberName("INFRA_ONE_NETWORK_ONEAPI_VirtualNetworkInterface_ungroup")]
    InfraOneNetworkOneapiVirtualNetworkInterfaceUngroup,
    [JsonStringEnumMemberName("INFRA_ONE_NETWORK_VirtualNetworkInterface_group")]
    InfraOneNetworkVirtualNetworkInterfaceGroup,
    [JsonStringEnumMemberName("INFRA_ONE_NETWORK_VirtualNetworkInterface_ungroup")]
    InfraOneNetworkVirtualNetworkInterfaceUngroup,
    [JsonStringEnumMemberName("addVirtualMac")]
    AddVirtualMac,
    [JsonStringEnumMemberName("addWindowSplaFromExistingSerial")]
    AddWindowSplaFromExistingSerial,
    [JsonStringEnumMemberName("applyBackupFtpAcls")]
    ApplyBackupFtpAcls,
    [JsonStringEnumMemberName("applyBackupFtpQuota")]
    ApplyBackupFtpQuota,
    [JsonStringEnumMemberName("bypassAntiDDosGame")]
    BypassAntiDDosGame,
    [JsonStringEnumMemberName("changePasswordBackupFTP")]
    ChangePasswordBackupFtp,
    [JsonStringEnumMemberName("changeRipeOrg")]
    ChangeRipeOrg,
    [JsonStringEnumMemberName("checkAndReleaseIp")]
    CheckAndReleaseIp,
    [JsonStringEnumMemberName("createBackupFTP")]
    CreateBackupFtp,
    [JsonStringEnumMemberName("createOrUpdateRipeOrg")]
    CreateOrUpdateRipeOrg,
    [JsonStringEnumMemberName("createPrivateNetwork")]
    CreatePrivateNetwork,
    [JsonStringEnumMemberName("disableFirewall")]
    DisableFirewall,
    [JsonStringEnumMemberName("enableFirewall")]
    EnableFirewall,
    [JsonStringEnumMemberName("genericMoveFloatingIp")]
    GenericMoveFloatingIp,
    [JsonStringEnumMemberName("hardReboot")]
    HardReboot,
    [JsonStringEnumMemberName("hardware_update")]
    HardwareUpdate,
    [JsonStringEnumMemberName("ipmi/configureSGX")]
    IpmiConfigureSgx,
    [JsonStringEnumMemberName("migrateBackupFTP")]
    MigrateBackupFtp,
    [JsonStringEnumMemberName("moveFloatingIp")]
    MoveFloatingIp,
    [JsonStringEnumMemberName("moveVirtualMac")]
    MoveVirtualMac,
    [JsonStringEnumMemberName("reagregateBlock")]
    ReagregateBlock,
    [JsonStringEnumMemberName("rebootPower8To")]
    RebootPower8To,
    [JsonStringEnumMemberName("reinstallServer")]
    ReinstallServer,
    [JsonStringEnumMemberName("releaseIp")]
    ReleaseIp,
    [JsonStringEnumMemberName("removeBackupFTP")]
    RemoveBackupFtp,
    [JsonStringEnumMemberName("removeVirtualMac")]
    RemoveVirtualMac,
    [JsonStringEnumMemberName("requestAccessIPMI")]
    RequestAccessIpmi,
    [JsonStringEnumMemberName("resetIPMI")]
    ResetIpmi,
    [JsonStringEnumMemberName("resetIPMISession")]
    ResetIpmiSession,
    [JsonStringEnumMemberName("testIPMIhttp")]
    TestIpmIhttp,
    [JsonStringEnumMemberName("testIPMIpassword")]
    TestIpmIpassword,
    [JsonStringEnumMemberName("testIPMIping")]
    TestIpmIping,
    [JsonStringEnumMemberName("virtualMacAdd")]
    VirtualMacAdd,
    [JsonStringEnumMemberName("virtualMacDelete")]
    VirtualMacDelete
}